version: "3"
services:
  frontend:
    build: ./front
    container_name: react-ui
    ports: 
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-app
  backend:
    build: ./back
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-app
  database:
    image: mongo:3.6.19-xenial
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local